### ISSUE TITLE
Facing error with KC 22

### ISSUE THREAD

**Issue by icemagno** [opensingular/singular-keycloak-database-federation#48]
```

2023-07-19 19:30:49,390 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-6) Uncaught server error: java.lang.AbstractMethodError: Receiver class org.opensingular.dbuserprovider.DBUserStorageProvider does not define or inherit an implementation of the resolved method 'abstract org.keycloak.models.UserModel getUserByUsername(org.keycloak.models.RealmModel, java.lang.String)' of interface org.keycloak.storage.user.UserLookupProvider.


	at org.keycloak.storage.UserStorageManager.lambda$getUserByUsername$16(UserStorageManager.java:334)


	at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:84)


	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)


	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)


	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)


	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)


	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)


	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)


	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)


	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)


	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)


	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)


	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)


	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)


	at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:334)


	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:269)


	at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:248)


	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:188)


	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUser(AbstractUsernameFormAuthenticator.java:167)


	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:148)


	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)


	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)


	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:154)


	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:986)


	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:323)


	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:294)


	at org.keycloak.services.resources.LoginActionsService.authenticateInternal(LoginActionsService.java:286)


	at org.keycloak.services.resources.LoginActionsService.access$100(LoginActionsService.java:111)


	at org.keycloak.services.resources.LoginActionsService$1.runInternal(LoginActionsService.java:266)


	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:67)


	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:44)


	at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)


	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:259)


	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:351)


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.base/java.lang.reflect.Method.invoke(Method.java:568)


	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)


	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)


	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)


	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)


	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)


	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)


	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)


	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)


	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)


	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)


	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)


	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)


	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)


	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)


	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)


	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)


	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)


	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)


	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)


	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)


	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)


	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)


	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)


	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)


	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)


	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)


	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)


	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)


	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)


	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)


	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)


	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)


	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)


	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)


	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)


	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)


	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)


	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)


	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)


	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)


	at java.base/java.lang.Thread.run(Thread.java:833)



```

**Comment by icemagno** [comment]
My fault. Sorry.
